-- Seed HSK 1-3 Vocabulary
-- Format: (hsk_level, chinese, traditional, pinyin, english, vietnamese, part_of_speech, example_zh, example_pinyin, example_en, stroke_count, frequency_rank)
INSERT INTO vocabulary (hsk_level, chinese, traditional, pinyin, english, vietnamese, part_of_speech, example_zh, example_pinyin, example_en, stroke_count, frequency_rank) VALUES
(1, '你好', NULL, 'nǐ hǎo', 'Hello / Hi', 'Xin chào', 'phrase', '你好，很高兴认识你。', 'Nǐ hǎo, hěn gāoxìng rènshi nǐ.', 'Hello, nice to meet you.', 7, 1),
(1, '谢谢', NULL, 'xièxie', 'Thank you', 'Cảm ơn', 'verb', '谢谢你的帮助！', 'Xièxie nǐ de bāngzhù!', 'Thank you for your help!', 12, 2),
(1, '我', NULL, 'wǒ', 'I / me', 'Tôi / tớ / tao', 'pronoun', '我是学生。', 'Wǒ shì xuésheng.', 'I am a student.', 7, 3),
(1, '你', NULL, 'nǐ', 'you (singular)', 'Bạn / cậu / anh / chị', 'pronoun', '你喜欢吃苹果吗？', 'Nǐ xǐhuan chī píngguǒ ma?', 'Do you like to eat apples?', 7, 4),
(1, '他', NULL, 'tā', 'he / him', 'Anh ấy / cậu ấy', 'pronoun', '他是我的汉语老师。', 'Tā shì wǒ de Hànyǔ lǎoshī.', 'He is my Chinese teacher.', 5, 5),
(1, '她', NULL, 'tā', 'she / her', 'Cô ấy / chị ấy', 'pronoun', '她去医院看医生了。', 'Tā qù yīyuàn kàn yīshēng le.', 'She went to the hospital to see a doctor.', 6, 6),
(1, '我们', NULL, 'wǒmen', 'we / us', 'Chúng tôi / chúng ta', 'pronoun', '我们明天一起去北京。', 'Wǒmen míngtiān yīqǐ qù Běijīng.', 'We will go to Beijing together tomorrow.', 12, 7),
(1, '你们', NULL, 'nǐmen', 'you (plural)', 'Các bạn / các anh', 'pronoun', '你们好！', 'Nǐmen hǎo!', 'Hello everyone!', 12, 8),
(1, '他们', NULL, 'tāmen', 'they / them (male/mixed)', 'Họ / bọn họ', 'pronoun', '他们是朋友。', 'Tāmen shì péngyou.', 'They are friends.', 10, 9),
(1, '她们', NULL, 'tāmen', 'they / them (female)', 'Các cô ấy / họ', 'pronoun', '她们在商店买衣服。', 'Tāmen zài shāngdiàn mǎi yīfu.', 'They are buying clothes in the shop.', 11, 10),
(1, '这', '這', 'zhè', 'this', 'Đây / này', 'pronoun', '这是什么书？', 'Zhè shì shénme shū?', 'What book is this?', 7, 11),
(1, '那', '那', 'nà', 'that', 'Đó / kia', 'pronoun', '那是我的电脑。', 'Nà shì wǒ de diànnǎo.', 'That is my computer.', 6, 12),
(1, '哪', '哪', 'nǎ', 'which / where', 'Nào / đâu', 'pronoun', '哪个人是你的朋友？', 'Nǎ ge rén shì nǐ de péngyou?', 'Which person is your friend?', 9, 13),
(1, '谁', '誰', 'shéi', 'who / whom', 'Ai', 'pronoun', '他是谁？', 'Tā shì shéi?', 'Who is he?', 10, 14),
(1, '什么', '什麼', 'shénme', 'what', 'Cái gì / gì', 'pronoun', '你在吃什么？', 'Nǐ zài chī shénme?', 'What are you eating?', 7, 15),
(1, '多少', NULL, 'duōshao', 'how much / how many', 'Bao nhiêu', 'pronoun', '这件衣服多少钱？', 'Zhè jiàn yīfu duōshao qián?', 'How much is this clothing?', 6, 16),
(1, '几', '幾', 'jǐ', 'how many / a few', 'Mấy / vài', 'pronoun', '你家里有几个人？', 'Nǐ jiā lǐ yǒu jǐ ge rén?', 'How many people are in your family?', 2, 17),
(1, '不', NULL, 'bù', 'no / not', 'Không', 'adverb', '我不喜欢喝茶。', 'Wǒ bù xǐhuan hē chá.', 'I do not like to drink tea.', 4, 18),
(1, '很', NULL, 'hěn', 'very', 'Rất', 'adverb', '今天天气很好。', 'Jīntiān tiānqì hěn hǎo.', 'The weather is very good today.', 9, 19),
(1, '太', NULL, 'tài', 'too / extremely', 'Quá / lắm', 'adverb', '这个杯子太小了。', 'Zhège bēizi tài xiǎo le.', 'This cup is too small.', 4, 20),
(1, '都', NULL, 'dōu', 'all / both', 'Đều', 'adverb', '我们都喜欢汉语。', 'Wǒmen dōu xǐhuan Hànyǔ.', 'We all like Chinese.', 10, 21),
(1, '和', NULL, 'hé', 'and / with', 'Và / với', 'conjunction', '我和你是好朋友。', 'Wǒ hé nǐ shì hǎo péngyou.', 'You and I are good friends.', 8, 22),
(1, '在', NULL, 'zài', 'at / in / on', 'Ở / đang', 'preposition', '他在家里睡觉。', 'Tā zài jiā lǐ shuìjiào.', 'He is sleeping at home.', 6, 23),
(1, '的', NULL, 'de', 'possessive particle', 'Của', 'particle', '这是我的苹果。', 'Zhè shì wǒ de píngguǒ.', 'This is my apple.', 8, 24),
(1, '了', NULL, 'le', 'past/completed action particle', 'Rồi / rồi', 'particle', '我吃米饭了。', 'Wǒ chī mǐfàn le.', 'I have eaten rice.', 2, 25),
(1, '吗', '嗎', 'ma', 'question particle', 'Không (hỏi)', 'particle', '你是老师吗？', 'Nǐ shì lǎoshī ma?', 'Are you a teacher?', 6, 26),
(1, '呢', NULL, 'ne', 'queries about status', 'Thì sao / nhỉ', 'particle', '我很热，你呢？', 'Wǒ hěn rè, nǐ ne?', 'I am very hot, how about you?', 8, 27),
(1, '个', '個', 'gè', 'general measure word', 'Cái / chiếc', 'measure', '我有一个弟弟。', 'Wǒ yǒu yī ge dìdi.', 'I have one younger brother.', 3, 28),
(1, '岁', '歲', 'suì', 'years of age', 'Tuổi', 'measure', '我儿子今年五岁了。', 'Wǒ érzi jīnnián wǔ suì le.', 'My son is five years old this year.', 6, 29),
(1, '本', NULL, 'běn', 'measure word for books', 'Cuốn / quyển', 'measure', '我买了一本书。', 'Wǒ mǎi le yī běn shū.', 'I bought a book.', 5, 30),
(1, '些', NULL, 'xiē', 'some / few', 'Những / một số', 'measure', '这些苹果很好吃。', 'Zhēxiē píngguǒ hěn hǎochī.', 'These apples are very delicious.', 8, 31),
(1, '块', '塊', 'kuài', 'piece / unit of currency', 'Cục / miếng / đồng', 'measure', '这块桌子很脏。', 'Zhè kuài zhuōzi hěn zāng.', 'This table is very dirty.', 7, 32),
(1, '一', NULL, 'yī', 'one', 'Một', 'numeral', '我要一个苹果。', 'Wǒ yào yī ge píngguǒ.', 'I want an apple.', 1, 33),
(1, '二', NULL, 'èr', 'two', 'Hai', 'numeral', '我有两个杯子。', 'Wǒ yǒu liǎng ge bēizi.', 'I have two cups.', 2, 34),
(1, '三', NULL, 'sān', 'three', 'Ba', 'numeral', '我写了三个汉字。', 'Wǒ xiě le sān ge Hànzì.', 'I wrote three Chinese characters.', 3, 35),
(1, '四', NULL, 'sì', 'four', 'Bốn', 'numeral', '他下午四点去商店。', 'Tā xiàwǔ sì diǎn qù shāngdiàn.', 'He will go to the store at 4 PM.', 5, 36),
(1, '五', NULL, 'wǔ', 'five', 'Năm', 'numeral', '我家有五个人。', 'Wǒ jiā yǒu wǔ ge rén.', 'My family has five people.', 4, 37),
(1, '六', NULL, 'liù', 'six', 'Sáu', 'numeral', '星期六我们去北京。', 'Xīngqīliù wǒmen qù Běijīng.', 'We are going to Beijing on Saturday.', 4, 38),
(1, '七', NULL, 'qī', 'seven', 'Bảy', 'numeral', '他今年七岁了。', 'Tā jīnnián qī suì le.', 'He is seven years old this year.', 2, 39),
(1, '八', NULL, 'bā', 'eight', 'Tám', 'numeral', '这杯水八块钱。', 'Zhè bēi shuǐ bā kuài qián.', 'This glass of water costs 8 yuan.', 2, 40),
(1, '九', NULL, 'jiǔ', 'nine', 'Chín', 'numeral', '九点我们要开会。', 'Jiǔ diǎn wǒmen yào kāihuì.', 'We have a meeting at 9 o''clock.', 2, 41),
(1, '十', NULL, 'shí', 'ten', 'Mười', 'numeral', '桌子上有十个杯子。', 'Zhuōzi shang yǒu shí ge bēizi.', 'There are ten cups on the table.', 2, 42),
(1, '零', NULL, 'líng', 'zero', 'Không (số)', 'numeral', '今天是二零二六年。', 'Jīntiān shì èr líng èr liù nián.', 'Today is the year 2026.', 13, 43),
(1, '家', NULL, 'jiā', 'home / family', 'Nhà / gia đình', 'noun', '我喜欢我的家。', 'Wǒ xǐhuan wǒ de jiā.', 'I like my home.', 10, 44),
(1, '学校', '學校', 'xuéxiào', 'school', 'Trường học', 'noun', '我们的学校很大。', 'Wǒmen de xuéxiào hěn dà.', 'Our school is very big.', 16, 45),
(1, '商店', NULL, 'shāngdiàn', 'shop / store', 'Cửa hàng', 'noun', '我去商店买衣服。', 'Wǒ qù shāngdiàn mǎi yīfu.', 'I go to the store to buy clothes.', 19, 46),
(1, '医院', '醫院', 'yīyuàn', 'hospital', 'Bệnh viện', 'noun', '医生在医院工作。', 'Yīshēng zài yīyuàn gōngzuò.', 'Doctors work in hospitals.', 16, 47),
(1, '火车', '火車', 'huǒchē', 'train', 'Tàu hỏa', 'noun', '火车站离这儿很近。', 'Huǒchēzhàn lí zhèr hěn jìn.', 'The train station is very close to here.', 11, 48),
(1, '飞机', '飛機', 'fēijī', 'airplane', 'Máy bay', 'noun', '他坐飞机去中国。', 'Tā zuò fēijī qù Zhōngguó.', 'He takes a plane to China.', 14, 49),
(1, '出租车', '出租車', 'chūzūchē', 'taxi', 'Xe taxi', 'noun', '我们坐出租车去学校。', 'Wǒmen zuò chūzūchē qù xuéxiào.', 'We take a taxi to school.', 22, 50),
(1, '电视', '電視', 'diànshì', 'television / TV', 'Tivi', 'noun', '我爸爸喜欢看电视。', 'Wǒ bàba xǐhuan kàn diànshì.', 'My father likes watching television.', 15, 51),
(1, '电脑', '電腦', 'diànnǎo', 'computer', 'Máy tính', 'noun', '我买了一个新电脑。', 'Wǒ mǎi le yī ge xīn diànnǎo.', 'I bought a new computer.', 22, 52),
(1, '电影', '電影', 'diànyǐng', 'movie / film', 'Phim điện ảnh', 'noun', '你喜欢看中国电影吗？', 'Nǐ xǐhuan kàn Zhōngguó diànyǐng ma?', 'Do you like to watch Chinese movies?', 14, 53),
(1, '天气', '天氣', 'tiānqì', 'weather', 'Thời tiết', 'noun', '明天的天气怎么样？', 'Míngtiān de tiānqì zěnmeyàng?', 'How will the weather be tomorrow?', 10, 54),
(1, '猫', '貓', 'māo', 'cat', 'Con mèo', 'noun', '这只猫很漂亮。', 'Zhè zhī māo hěn piàoliang.', 'This cat is very beautiful.', 11, 55),
(1, '狗', NULL, 'gǒu', 'dog', 'Con chó', 'noun', '我家有一只可爱的狗。', 'Wǒ jiā yǒu yī zhī kě’ài de gǒu.', 'My family has a cute dog.', 8, 56),
(1, '东西', '東西', 'dōngxi', 'things / stuff', 'Đồ đạc / thứ', 'noun', '你在商店买什么东西？', 'Nǐ zài shāngdiàn mǎi shénme dōngxi?', 'What things did you buy at the store?', 14, 57),
(1, '水', NULL, 'shuǐ', 'water', 'Nước', 'noun', '我要喝一杯水。', 'Wǒ yào hē yī bēi shuǐ.', 'I want to drink a cup of water.', 4, 58),
(1, '茶', NULL, 'chá', 'tea', 'Trà / chè', 'noun', '中国人喜欢喝茶。', 'Zhōngguórén xǐhuan hē chá.', 'Chinese people like to drink tea.', 9, 59),
(1, '米饭', '米飯', 'mǐfàn', 'cooked rice', 'Cơm', 'noun', '我中午吃米饭和菜。', 'Wǒ zhōngwǔ chī mǐfàn hé cài.', 'I eat rice and dishes at noon.', 13, 60),
(1, '苹果', '蘋果', 'píngguǒ', 'apple', 'Quả táo', 'noun', '苹果很好吃。', 'Píngguǒ hěn hǎochī.', 'Apples are very tasty.', 16, 61),
(1, '菜', NULL, 'cài', 'dish / vegetable', 'Rau / món ăn', 'noun', '妈妈在做菜。', 'Māma zài zuò cài.', 'Mom is cooking dishes.', 11, 62),
(1, '衣服', NULL, 'yīfu', 'clothes / clothing', 'Quần áo', 'noun', '这件衣服很漂亮。', 'Zhè jiàn yīfu hěn piàoliang.', 'This piece of clothing is very beautiful.', 14, 63),
(1, '书', '書', 'shū', 'book', 'Sách', 'noun', '桌子上有三本书。', 'Zhuōzi shang yǒu sān běn shū.', 'There are three books on the table.', 4, 64),
(1, '汉语', '漢語', 'Hànyǔ', 'Chinese language', 'Tiếng Trung', 'noun', '我们在学习汉语。', 'Wǒmen zài xuéxí Hànyǔ.', 'We are studying Chinese.', 21, 65),
(1, '汉字', '漢字', 'Hànzì', 'Chinese characters', 'Chữ Hán', 'noun', '写汉字不难。', 'Xiě Hànzì bù nán.', 'Writing Chinese characters is not hard.', 11, 66),
(1, '钱', '錢', 'qián', 'money', 'Tiền', 'noun', '我没有钱买这个电脑。', 'Wǒ méiyǒu qián mǎi zhège diànnǎo.', 'I don''t have money to buy this computer.', 10, 67),
(1, '名字', NULL, 'míngzi', 'name', 'Tên', 'noun', '你的名字是什么？', 'Nǐ de míngzi shì shénme?', 'What is your name?', 12, 68),
(1, '老师', '老師', 'lǎoshī', 'teacher', 'Thầy giáo / cô giáo', 'noun', '李老师在教汉语。', 'Lǐ lǎoshī zài jiāo Hànyǔ.', 'Teacher Li is teaching Chinese.', 16, 69),
(1, '学生', '學生', 'xuésheng', 'student', 'Học sinh / sinh viên', 'noun', '他是我们学校的学生。', 'Tā shì wǒmen xuéxiào de xuésheng.', 'He is a student at our school.', 13, 70),
(1, '同学', '同學', 'tóngxué', 'classmate', 'Bạn cùng học', 'noun', '我和我的同学一起学习。', 'Wǒ hé wǒ de tóngxué yīqǐ xuéxí.', 'I study together with my classmate.', 13, 71),
(1, '朋友', NULL, 'péngyou', 'friend', 'Bạn bè', 'noun', '他是我的好朋友。', 'Tā shì wǒ de hǎo péngyou.', 'He is my good friend.', 12, 72),
(1, '医生', '醫生', 'yīshēng', 'doctor', 'Bác sĩ', 'noun', '李医生在医院工作。', 'Lǐ yīshēng zài yīyuàn gōngzuò.', 'Doctor Li works in the hospital.', 12, 73),
(1, '爸爸', NULL, 'bàba', 'father / dad', 'Bố / cha', 'noun', '我爸爸喜欢喝咖啡。', 'Wǒ bàba xǐhuan hē kāfēi.', 'My dad likes to drink coffee.', 16, 74),
(1, '妈妈', '媽媽', 'māma', 'mother / mom', 'Mẹ / má', 'noun', '我妈妈在做饭。', 'Wǒ māma zài zuòfàn.', 'My mom is cooking food.', 12, 75),
(1, '儿子', '兒子', 'érzi', 'son', 'Con trai', 'noun', '我儿子今年八岁。', 'Wǒ érzi jīnnián bā suì.', 'My son is eight years old.', 5, 76),
(1, '女儿', '女兒', 'nǚ''ér', 'daughter', 'Con gái', 'noun', '他女儿在学校学习。', 'Tā nǚ''ér zài xuéxiào xuéxí.', 'His daughter studies at school.', 6, 77),
(1, '先生', NULL, 'xiānsheng', 'Mr. / husband', 'Ông / ngài / chồng', 'noun', '王先生去北京了。', 'Wáng xiānsheng qù Běijīng le.', 'Mr. Wang went to Beijing.', 11, 78),
(1, '小姐', NULL, 'xiǎojiě', 'Miss / young lady', 'Cô / tiểu thư', 'noun', '张小姐在买衣服。', 'Zhāng xiǎojiě zài mǎi yīfu.', 'Miss Zhang is buying clothes.', 6, 79),
(1, '年', NULL, 'nián', 'year', 'Năm', 'noun', '我在中国住了三年。', 'Wǒ zài Zhōngguó zhù le sān nián.', 'I lived in China for three years.', 6, 80),
(1, '月', NULL, 'yuè', 'month', 'Tháng', 'noun', '今天是十二月一日。', 'Jīntiān shì shí''èr yuè yī rì.', 'Today is December 1st.', 4, 81),
(1, '日', NULL, 'rì', 'day / date', 'Ngày', 'noun', '我的生日是九月十日。', 'Wǒ de shēngrì shì jiǔ yuè shí rì.', 'My birthday is September 10th.', 4, 82),
(1, '星期', NULL, 'xīngqī', 'week', 'Tuần / thứ', 'noun', '星期天我去学校。', 'Xīngqītīan wǒ qù xuéxiào.', 'I go to school on Sunday.', 21, 83),
(1, '点', '點', 'diǎn', 'o''clock / dot / click', 'Giờ / điểm', 'noun', '现在是下午两点。', 'Xiànzài shì xiàwǔ liǎng diǎn.', 'It is 2 PM now.', 9, 84),
(1, '分钟', '分鐘', 'fēnzhōng', 'minute', 'Phút', 'noun', '我等了你十分钟。', 'Wǒ děng le nǐ shí fēnzhōng.', 'I waited for you for ten minutes.', 14, 85),
(1, '现在', '現在', 'xiànzài', 'now', 'Bây giờ', 'noun', '现在几点了？', 'Xiànzài jǐ diǎn le?', 'What time is it now?', 14, 86),
(1, '时候', '時候', 'shíhou', 'time / moment', 'Lúc / khi', 'noun', '你什么时候去北京？', 'Nǐ shénme shíhou qù Běijīng?', 'When are you going to Beijing?', 20, 87),
(1, '今天', NULL, 'jīntiān', 'today', 'Hôm nay', 'noun', '今天天气非常好。', 'Jīntiān tiānqì fēicháng hǎo.', 'Today the weather is very good.', 8, 88),
(1, '昨天', NULL, 'zuótiān', 'yesterday', 'Hôm qua', 'noun', '昨天晚上我没看电影。', 'Zuótiān wǎnshang wǒ méi kàn diànyǐng.', 'Yesterday evening I didn''t watch a movie.', 14, 89),
(1, '明天', NULL, 'míngtiān', 'tomorrow', 'Ngày mai', 'noun', '明天我们要上汉语课。', 'Míngtiān wǒmen yào shàng Hànyǔ kè.', 'Tomorrow we will have a Chinese class.', 12, 90),
(1, '早上', NULL, 'zǎoshang', 'morning', 'Buổi sáng', 'noun', '早上好，你吃早饭了吗？', 'Zǎoshang hǎo, nǐ chī zǎofàn le ma?', 'Good morning, have you had breakfast?', 11, 91),
(1, '中午', NULL, 'zhōngwǔ', 'noon / midday', 'Buổi trưa', 'noun', '我中午在学校吃饭。', 'Wǒ zhōngwǔ zài xuéxiào chīfàn.', 'I eat at school at noon.', 8, 92),
(1, '下午', NULL, 'xiàwǔ', 'afternoon', 'Buổi chiều', 'noun', '下午我去火车站买票。', 'Xiàwǔ wǒ qù huǒchēzhàn mǎi piào.', 'In the afternoon I go to the train station to buy a ticket.', 6, 93),
(1, '晚上', NULL, 'wǎnshang', 'evening / night', 'Buổi tối', 'noun', '今天晚上我和朋友见面。', 'Jīntiān wǎnshang wǒ hé péngyou jiànmiàn.', 'Tonight I will meet my friends.', 11, 94),
(1, '上', NULL, 'shàng', 'up / above / previous', 'Trên / lên', 'noun', '桌子上有一只猫。', 'Zhuōzi shang yǒu yī zhī māo.', 'There is a cat on the table.', 3, 95),
(1, '下', NULL, 'xià', 'down / below / next', 'Dưới / xuống', 'noun', '椅子下面有一只狗。', 'Yǐzi xiàmiàn yǒu yī zhī gǒu.', 'There is a dog under the chair.', 3, 96),
(1, '前', NULL, 'qián', 'front / before', 'Trước', 'noun', '三年前我不会说汉语。', 'Sān nián qián wǒ bù huì shuō Hànyǔ.', 'Three years ago I couldn''t speak Chinese.', 9, 97),
(1, '后', '後', 'hòu', 'back / behind / after', 'Sau', 'noun', '火车站后面是我们的学校。', 'Huǒchēzhàn hòumiàn shì wǒmen de xuéxiào.', 'Behind the train station is our school.', 6, 98),
(1, '里', '裡', 'lǐ', 'inside / in', 'Trong', 'noun', '杯子里有水吗？', 'Bēizi lǐ yǒu shuǐ ma?', 'Is there water in the cup?', 7, 99),
(1, '这儿', '這兒', 'zhèr', 'here', 'Ở đây', 'pronoun', '请在这儿写你的名字。', 'Qǐng zài zhèr xiě nǐ de míngzi.', 'Please write your name here.', 13, 100),
(1, '那儿', '那兒', 'nàr', 'there', 'Ở kia', 'pronoun', '我的电脑在那儿。', 'Wǒ de diànnǎo zài nàr.', 'My computer is over there.', 12, 101),
(1, '哪儿', '哪兒', 'nǎr', 'where', 'Ở đâu', 'pronoun', '你的家在哪儿？', 'Nǐ de jiā zài nǎr?', 'Where is your home?', 15, 102),
(1, '是', NULL, 'shì', 'to be / yes', 'Là / vâng / đúng', 'verb', '他是我们的医生。', 'Tā shì wǒmen de yīshēng.', 'He is our doctor.', 9, 103),
(1, '有', NULL, 'yǒu', 'to have / there is', 'Có', 'verb', '我有一个漂亮的猫。', 'Wǒ yǒu yī ge piàoliang de māo.', 'I have a beautiful cat.', 6, 104),
(1, '看', NULL, 'kàn', 'to look / watch / read', 'Nhìn / xem / đọc', 'verb', '我喜欢看中国电影。', 'Wǒ xǐhuan kàn Zhōngguó diànyǐng.', 'I like to watch Chinese movies.', 9, 105),
(1, '听', '聽', 'tīng', 'to listen / hear', 'Nghe', 'verb', '你听，谁在唱歌？', 'Nǐ tīng, shéi zài chànggē?', 'Listen, who is singing?', 7, 106),
(1, '说', '說', 'shuō', 'to speak / say', 'Nói', 'verb', '你会说汉语吗？', 'Nǐ huì shuō Hànyǔ ma?', 'Can you speak Chinese?', 9, 107),
(1, '读', '讀', 'dú', 'to read / study', 'Đọc', 'verb', '请大声读这个汉字。', 'Qǐng dàshēng dú zhège Hànzì.', 'Please read this Chinese character out loud.', 10, 108),
(1, '写', '寫', 'xiě', 'to write', 'Viết', 'verb', '这个字怎么写？', 'Zhège zì zěnmeyàng xiě?', 'How do you write this character?', 5, 109),
(1, '听见', '聽見', 'tīngjiàn', 'to hear', 'Nghe thấy', 'verb', '我听见有人在叫我。', 'Wǒ tīngjiàn yǒurén zài jiào wǒ.', 'I heard someone calling me.', 14, 110),
(1, '看见', '看見', 'kànjiàn', 'to see / catch sight of', 'Nhìn thấy', 'verb', '我昨天在商店看见你了。', 'Wǒ zuótiān zài shāngdiàn kànjiàn nǐ le.', 'I saw you at the store yesterday.', 16, 111),
(1, '叫', NULL, 'jiào', 'to call / be called', 'Gọi / tên là', 'verb', '我叫大卫，你呢？', 'Wǒ jiào Dàwèi, nǐ ne?', 'My name is David, what about you?', 5, 112),
(1, '来', '來', 'lái', 'to come / arrive', 'Đến / lại', 'verb', '李老师明天来我家。', 'Lǐ lǎoshī míngtiān lái wǒ jiā.', 'Teacher Li is coming to my house tomorrow.', 7, 113),
(1, '回', NULL, 'huí', 'to return / go back', 'Về / quay lại', 'verb', '他下星期回国。', 'Tā xià xīngqī huíguó.', 'He will return to his country next week.', 6, 114),
(1, '去', NULL, 'qù', 'to go / leave', 'Đi', 'verb', '明天我和姐姐去医院。', 'Míngtiān wǒ hé jiějie qù yīyuàn.', 'Tomorrow my older sister and I are going to the hospital.', 5, 115),
(1, '吃', NULL, 'chī', 'to eat', 'Ăn', 'verb', '你喜欢吃什么中国菜？', 'Nǐ xǐhuan chī shénme Zhōngguócài?', 'What Chinese dishes do you like to eat?', 6, 116),
(1, '喝', NULL, 'hē', 'to drink', 'Uống', 'verb', '我要喝一杯水。', 'Wǒ yào hē yī bēi shuǐ.', 'I want to drink a glass of water.', 12, 117),
(1, '睡觉', '睡覺', 'shuìjiào', 'to sleep', 'Ngủ', 'verb', '太晚了，我要睡觉了。', 'Tài wǎn le, wǒ yào shuìjiào le.', 'It''s too late, I am going to sleep.', 13, 118),
(1, '打电话', '打電話', 'dǎ diànhuà', 'to make a phone call', 'Gọi điện thoại', 'verb', '我下午给妈妈打电话。', 'Wǒ xiàwǔ gěi māma dǎ diànhuà.', 'I will call my mom in the afternoon.', 13, 119),
(1, '做', NULL, 'zuò', 'to do / make', 'Làm', 'verb', '你在做什么？', 'Nǐ zài zuò shénme?', 'What are you doing?', 11, 120),
(1, '买', '買', 'mǎi', 'to buy', 'Mua', 'verb', '我想买一个新电视。', 'Wǒ xiǎng mǎi yī ge xīn diànshì.', 'I want to buy a new television.', 6, 121),
(1, '开', '開', 'kāi', 'to open / drive / turn on', 'Mở / lái / bật', 'verb', '请把电脑开一下。', 'Qǐng bǎ diànnǎo kāi yīxià.', 'Please turn on the computer.', 4, 122),
(1, '坐', NULL, 'zuò', 'to sit / take (vehicle)', 'Ngồi / đi (xe)', 'verb', '请坐下，我们喝茶。', 'Qǐng zuò xià, wǒmen hē chá.', 'Please sit down, let''s drink tea.', 7, 123),
(1, '住', NULL, 'zhù', 'to live / reside', 'Trú / ở / sinh sống', 'verb', '你住在哪个房间？', 'Nǐ zhù zài nǎge fángjiān?', 'Which room are you staying in?', 7, 124),
(1, '学习', '學習', 'xuéxí', 'to study / learn', 'Học / học tập', 'verb', '我们要好好学习汉语。', 'Wǒmen yào hǎohǎo xuéxí Hànyǔ.', 'We need to study Chinese well.', 19, 125),
(1, '工作', NULL, 'gōngzuò', 'to work / job', 'Làm việc / công việc', 'verb', '他在火车站工作。', 'Tā zài huǒchēzhàn gōngzuò.', 'He works at the train station.', 10, 126),
(1, '喜欢', '喜歡', 'xǐhuan', 'to like / love', 'Thích', 'verb', '我很喜欢看中国电影。', 'Wǒ hěn xǐhuan kàn Zhōngguó diànyǐng.', 'I like watching Chinese movies very much.', 12, 127),
(1, '想', NULL, 'xiǎng', 'to want / think / miss', 'Muốn / nghĩ / nhớ', 'verb', '我想吃米饭。', 'Wǒ xiǎng chī mǐfàn.', 'I want to eat rice.', 13, 128),
(1, '会', '會', 'huì', 'can / be able to / meeting', 'Biết / sẽ / hội', 'verb', '我会说一点汉语。', 'Wǒ huì shuō yīdiǎn Hànyǔ.', 'I can speak a little Chinese.', 6, 129),
(1, '能', NULL, 'néng', 'can / may', 'Có thể', 'verb', '今天下雨，我不能去。', 'Jīntiān xià yǔ, wǒ bù néng qù.', 'It is raining today, I cannot go.', 10, 130),
(1, '认识', '認識', 'rènshi', 'to know / recognize', 'Quen biết / nhận biết', 'verb', '认识你很高兴。', 'Rènshi nǐ hěn gāoxìng.', 'Nice to meet you.', 9, 131),
(1, '大', NULL, 'dà', 'big / large', 'To / lớn', 'adjective', '这个西瓜很大。', 'Zhège xīguā hěn dà.', 'This watermelon is very big.', 3, 132),
(1, '小', NULL, 'xiǎo', 'small / little', 'Nhỏ / bé', 'adjective', '我家有一只小猫。', 'Wǒ jiā yǒu yī zhī xiǎo māo.', 'My house has a small cat.', 3, 133),
(1, '多', NULL, 'duō', 'many / much', 'Nhiều', 'adjective', '今天来学校的人很多。', 'Jīntiān lái xuéxiào de rén hěn duō.', 'Many people came to school today.', 6, 134),
(1, '少', NULL, 'shǎo', 'few / little', 'Ít', 'adjective', '杯子里的水很少。', 'Bēizi lǐ de shuǐ hěn shǎo.', 'There is very little water in the cup.', 4, 135),
(1, '冷', NULL, 'lěng', 'cold', 'Lạnh', 'adjective', '今天太冷了，我不想出去。', 'Jīntiān tài lěng le, wǒ bù xiǎng chūqù.', 'Today is too cold, I don''t want to go out.', 7, 136),
(1, '热', '熱', 'rè', 'hot', 'Nóng', 'adjective', '房间里太热了。', 'Fángjiān lǐ tài rè le.', 'It is too hot in the room.', 10, 137),
(1, '漂亮', NULL, 'piàoliang', 'beautiful / pretty', 'Đẹp / xinh đẹp', 'adjective', '你写的汉字很漂亮。', 'Nǐ xiě de Hànzì hěn piàoliang.', 'The Chinese characters you write are very beautiful.', 20, 138),
(1, '高兴', '高興', 'gāoxìng', 'happy / glad', 'Vui vẻ / phấn khởi', 'adjective', '认识你，我很高兴。', 'Rènshi nǐ, wǒ hěn gāoxìng.', 'Nice to meet you, I am very happy.', 20, 139),
(1, '再见', '再見', 'zàijiàn', 'Goodbye', 'Tạm biệt', 'phrase', '老师，再见！', 'Lǎoshī, zàijiàn!', 'Goodbye, teacher!', 10, 140),
(1, '对不起', '對不起', 'duìbuqǐ', 'Sorry / excuse me', 'Xin lỗi', 'phrase', '对不起，我迟到了。', 'Duìbuqǐ, wǒ chídào le.', 'Sorry, I am late.', 12, 141),
(1, '没关系', '沒關係', 'méi guānxi', 'It doesn''t matter', 'Không sao đâu', 'phrase', '对不起！——没关系。', 'Duìbuqǐ! —— Méi guānxi.', 'Sorry! —— It''s okay.', 16, 142),
(1, '请', '請', 'qǐng', 'please / invite', 'Mời / xin', 'verb', '请坐下，喝杯茶。', 'Qǐng zuò xià, hē bēi chá.', 'Please sit down and have a cup of tea.', 10, 143),
(1, '喂', NULL, 'wèi', 'hello (on phone)', 'Alo (điện thoại)', 'interjection', '喂，你是李医生吗？', 'Wèi, nǐ shì Lǐ yīshēng ma?', 'Hello, are you Doctor Li?', 12, 144),
(1, '家', NULL, 'jiā', 'home / family', 'Nhà', 'noun', '我爱我家。', 'Wǒ ài wǒ jiā.', 'I love my family.', 10, 145),
(1, '客气', '客氣', 'kèqi', 'polite / courteous', 'Khách sáo', 'adjective', '别客气，这是我应该做的。', 'Bié kèqi, zhè shì wǒ yīnggāi zuò de.', 'You''re welcome, it is my duty.', 15, 146),
(1, '衣服', NULL, 'yīfu', 'clothes', 'Quần áo', 'noun', '洗衣服。', 'Xǐ yīfu.', 'Wash clothes.', 14, 147),
(1, '这儿', '這兒', 'zhèr', 'here', 'Ở đây', 'pronoun', '来这儿。', 'Lái zhèr.', 'Come here.', 13, 148),
(1, '认识', '認識', 'rènshi', 'to know', 'Quen biết', 'verb', '我认识他。', 'Wǒ rènshi tā.', 'I know him.', 9, 149),
(1, '谢谢', NULL, 'xièxie', 'thanks', 'Cảm ơn', 'verb', '谢谢大家。', 'Xièxie dàjiā.', 'Thank you, everyone.', 12, 150),
(2, '考试', '考試', 'kǎoshì', 'exam / test', 'Thi / kiểm tra', 'noun', '明天的考试很重要。', 'Míngtiān de kǎoshì hěn zhòngyào.', 'Tomorrow''s exam is very important.', 12, 151),
(2, '便宜', NULL, 'piányi', 'cheap', 'Rẻ', 'adjective', '商店里的东西很便宜。', 'Shāngdiàn lǐ de dōngxi hěn piányi.', 'The things in the store are very cheap.', 15, 152),
(3, '容易', NULL, 'róngyì', 'easy', 'Dễ dàng', 'adjective', '写汉字不容易。', 'Xiě Hànzì bù róngyì.', 'Writing Chinese characters is not easy.', 18, 153);

-- Seed HSK Lessons
-- Note: content_zh, content_pinyin, content_en, content_vi are structured strings (or arrays of sentences) to support sentence-by-sentence layouts.
-- We will store them as JSON string arrays so they can be parsed by Hono/React easily.
INSERT INTO lessons (title_zh, title_en, hsk_level, content_zh, content_pinyin, content_en, content_vi, audio_url, category) VALUES
(
  '在学校的第一天',
  'First Day at School',
  1,
  '["你好！","我是王小明。","今天是我在学校的第一天。","我认识了很多新同学和老师。","我们的学校非常大，也很漂亮。","我非常喜欢学习汉语。"]',
  '["Nǐ hǎo!","Wǒ shì Wáng Xiǎomíng.","Jīntiān shì wǒ zài xuéxiào de dì-yī tiān.","Wǒ rènshi le hěn duō xīn tóngxué hé lǎoshī.","Wǒmen de xuéxiào fēicháng dà, yě hěn piàoliang.","Wǒ fēicháng xǐhuan xuéxí Hànyǔ."]',
  '["Hello!","I am Wang Xiaoming.","Today is my first day at school.","I got to know many new classmates and teachers.","Our school is extremely big, and also very beautiful.","I like learning Chinese very much."]',
  '["Xin chào!","Tôi là Vương Tiểu Minh.","Hôm nay là ngày đầu tiên của tôi ở trường.","Tôi đã quen biết rất nhiều bạn học mới và thầy cô.","Trường học của chúng tôi rất lớn, cũng rất đẹp.","Tôi cực kỳ thích học tiếng Trung."]',
  NULL,
  'daily'
),
(
  '去中国旅游',
  'Traveling to China',
  1,
  '["下个月我要去中国旅游。","我想去北京看万里长城。","我还要坐飞机去上海。","我会在中国住十天。","我希望能和中国人说汉语。","谢谢我的老师教我汉语。"]',
  '["Xià ge yuè wǒ yào qù Zhōngguó lǚyóu.","Wǒ xiǎng qù Běijīng kàn Wànlǐ Chángchéng.","Wǒ hái yào zuò fēijī qù Shànghǎi.","Wǒ huì zài Zhōngguó zhù shí tiān.","Wǒ xīwàng néng hé Zhōngguórén shuō Hànyǔ.","Xièxie wǒ de lǎoshī jiāo wǒ Hànyǔ."]',
  '["Next month I will travel to China.","I want to go to Beijing to see the Great Wall.","I also need to take a plane to Shanghai.","I will stay in China for ten days.","I hope I can speak Chinese with Chinese people.","Thank you, my teacher, for teaching me Chinese."]',
  '["Tháng sau tôi sẽ đi du lịch Trung Quốc.","Tôi muốn đi Bắc Kinh xem Vạn Lý Trường Thành.","Tôi còn muốn đi máy bay đến Thượng Hải.","Tôi sẽ ở lại Trung Quốc mười ngày.","Tôi hy vọng có thể nói tiếng Trung với người Trung Quốc.","Cảm ơn thầy giáo đã dạy tiếng Trung cho tôi."]',
  NULL,
  'travel'
),
(
  '去饭馆吃中国菜',
  'Eating Chinese Food at a Restaurant',
  1,
  '["今天中午我和朋友去饭馆吃饭。","我们点了一些米饭、菜和茶。","这里的菜非常热，也很好吃。","我的朋友喜欢吃鱼，我喜欢吃牛肉。","我们都觉得这一块钱花得值。","谢谢！再见！"]',
  '["Jīntiān zhōngwǔ wǒ hé péngyou qù fànguǎn chīfàn.","Wǒmen diǎn le yīxiē mǐfàn, cài hé chá.","Zhèlǐ de cài fēicháng rè, yě hěn hǎochī.","Wǒ de péngyou xǐhuan chī yú, wǒ xǐhuan chī niúròu.","Wǒmen dōu juéde zhè yī kuài qián huā de zhí.","Xièxie! Zàijiàn!"]',
  '["Today at noon, my friend and I went to a restaurant to eat.","We ordered some rice, dishes, and tea.","The dishes here are very hot and also very delicious.","My friend likes eating fish, I like eating beef.","We both think this money was well spent.","Thank you! Goodbye!"]',
  '["Trưa hôm nay tôi và bạn tôi đi ăn ở nhà hàng.","Chúng tôi gọi một ít cơm, thức ăn và trà.","Đồ ăn ở đây rất nóng, cũng rất ngon.","Bạn tôi thích ăn cá, tôi thích ăn thịt bò.","Chúng tôi đều thấy số tiền bỏ ra rất xứng đáng.","Cảm ơn! Tạm biệt!"]',
  NULL,
  'daily'
);
